use_frameworks!

platform :ios, '8.0'

target 'DZLimaoSDK_Example' do
  pod 'DZLimaoSDK', :path => '../'

  target 'DZLimaoSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
